### ISSUE TITLE
Extra day displayed for task in gantt chart

### ISSUE THREAD

**Issue by TroyWilliams3687** [traherom/simple-scheduler#1]
I installed the library via pip and create a simple gantt chart based on the example csv file. It seems that all of the tasks have an extra day added to their duration when plotted in the chart. If the duration was 5 days, it would show up as 6 days.

**Comment by traherom** [comment]
Turns out I'm an idiot. Fixed now. 

Also made `pip install` work better and get `svgwrite` as well.

**Comment by TroyWilliams3687** [comment]
Cool! - Thanks. If you are interested I did a jupyter notebook as an alternative way to use your library.
