### ISSUE TITLE
Does not follow basic OOP principles, therefore is hard to modify & extend...

### ISSUE THREAD

**Issue by radimspetlik** [traherom/simple-scheduler#2]
Hi,

I am, of course, grateful to you for sharing your gantt scheduler with us.

However, I would like to recommend you to study OOP before doing any more coding, since your project is very badly designed.

Just as an example - you do
`self.project.add_task(self)` on l 490 in gantt.py, which does not make sense at all.

I wanted to extend your project but it would first need a complete revamp, so I won't be continuing in your work.

I recommend a very good book about software development

https://www.amazon.com/Growing-Object-Oriented-Software-Guided-Tests/dp/0321503627

Good luck with your next projects!

**Comment by traherom** [comment]
I'm definitely willing to believe this could be better--the drawing code is an unreadable mess if I recall correctly.

However, I'm genuinely curious why that particular line doesn't make sense. It appears to just ensure that when a task is assigned a project that the project is also appropriately assigned the task. What principle does that violate?

**Comment by radimspetlik** [comment]
Hi @traherom, from the SI perspective, (in this case) it does not make sense for the Task class to handle its registration to the Project class; a more correct version of the design would either construct the Project with the tasks available in the Project's constructor or first create Project instance (as you do) and then assign tasks to the project in some function or in a Project's method (which you do not do). The part of the code that I mentioned is just to give you a place where to begin the process of the redesign; as you probably guessed from the things that I already wrote - the whole structure of the project is less than optimal...

If you do want to improve your SI skills, I really recommend the book.

Good luck...

**Comment by traherom** [comment]
Thanks for your feedback! I won't be redesigning it, since it was a project for a one-time need.

I would like to gently suggest telling people to not code unless they meet every programming principle is perhaps not... Super helpful. Got to start somewhere and not every project warrants the same level of design.
